name: NetflixFrontend stack build-deploy

on:
  push:
    branches:
     - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        run: |
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      - uses: actions/checkout@v3
      - name: Buid and push docker images
        run: |
          IMAGE_NAME=guymeltzer/nf:${{ github.run_number }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Checkout infrastructure repo
        uses: actions/checkout@v3
        with:
          repository: https://github.com/guymeltzer/NetflixInfra  # TODO change me
          token: ${{ secrets.REPO_TOKEN }}  # The GITHUB_TOKEN secret is a GitHub access token.
          path: ./NetflixInfra

      - name: Update YAML manifests
        run: |
           cd ./NetflixInfra
           # TODO commit & push changes to infra repo
           

      - name: Commit and Push changes
        run: |
           cd ./NetflixInfra
           # TODO commit & push changes to infra repo