name: NetflixFrontend stack build-deploy

on:
  push:
    branches:
     - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/netflix-frontend:${{ github.sha }}

      - name: Checkout infrastructure repo
        uses: actions/checkout@v3
        with:
          repository: guymeltzer/NetflixInfra
          token: ${{ secrets.REPO_TOKEN }}
          path: ./NetflixInfra

      - name: Update YAML manifests
        run: |
          cd ./NetflixInfra/k8s/NetflixFrontend
          sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/netflix-frontend:${{ github.sha }}|' deployment.yaml

      - name: Commit and Push changes
        run: |
          cd ./NetflixInfra
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Netflix Frontend image to ${{ github.sha }}"
          git push
