name: NetflixFrontend stack build-deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - uses: actions/checkout@v3

      - name: Build and push docker images
        run: |
          IMAGE_NAME=guymeltzer/nf:${{ github.run_number }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Checkout infrastructure repo
        uses: actions/checkout@v3
        with:
          repository: guymeltzer/NetflixInfra  # Changed this line
          token: ${{ secrets.REPO_TOKEN }}
          path: ./NetflixInfra

      - name: Update YAML manifests
        run: |
          cd ./NetflixInfra
          sed -i "s|image: guymeltzer/nf:[0-9]*|image: guymeltzer/nf:${{ github.run_number }}|g" ./k8s/NetflixFrontend/deployment.yaml
          sed -i "s|image: guymeltzer/nf:[0-9]*|image: guymeltzer/nf:${{ github.run_number }}|g" ./k8s/NetflixMovieCatalog/deployment.yaml

      - name: Commit and Push changes
        run: |
          cd ./NetflixInfra
          git config --global user.name "Your Github Bot"
          git config --global user.email "yourbot@example.com"
          git add .
          git commit -m "Update image tag to ${{ github.run_number }}"
          git push origin main