name: NetflixFrontend stack build-deploy

on:
  push:
    branches:
     - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
      - run: |
          IMAGE_NAME=guymeltzer/nf
          COMMIT_ID=${{ github.sha }}
          SHORT_COMMIT_ID=${COMMIT_ID:0:7}
          docker build -t $IMAGE_NAME:$SHORT_COMMIT_ID .
          docker push $IMAGE_NAME:$SHORT_COMMIT_ID

      - name: Checkout infrastructure repo
        uses: actions/checkout@v3
        with:
          repository: guymeltzer/NetflixInfra
          token: ${{ secrets.REPO_TOKEN }}
          path: ./NetflixInfra

      - name: Update Kubernetes Manifests
        run: |
            cd ./NetflixInfra
            FRONTEND_DEPLOYMENT_FILE=k8s/NetflixFrontend/netflix-frontend-deploy.yaml
            IMAGE_NAME=guymeltzer/nf
            COMMIT_ID=${{ github.sha }}
            SHORT_COMMIT_ID=${COMMIT_ID:0:7}
            
            # Update the image tag in the deployment YAML
            sed -i "s|image: .*|image: $IMAGE_NAME:$SHORT_COMMIT_ID|g" $FRONTEND_DEPLOYMENT_FILE
#
      - name: Commit and Push changes
        run: |
          cd ./NetflixInfra
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Netflix Frontend image to ${{ github.sha }}"
          git push
